workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test
  - build

test:
  stage: test
  image: node:14-alpine
  script:
    - npm i --no-optional
    - npm run lint -- --no-fix
    - npm run test:unit

build:
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f Dockerfile.prod .
    - docker push $IMAGE_TAG
