FROM node:14-alpine AS builder

# make the 'app' folder the current working directory
WORKDIR /app
COPY package*.json ./
RUN npm install 
# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .
RUN npm run build

FROM caddy:2.4.5-alpine

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /app/dist ./

EXPOSE 80
