FROM node:alpine

ENV NODE_ENV=production

# make the 'app' folder the current working directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# install project dependencies and build app for production with minification
RUN npm install --quiet && npm run build

